<a href="https://colab.research.google.com/github/gaudhami4/task1/blob/main/PHONEBOOK.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install dnspython
!pip install pymongo[srv]

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: dnspython in /usr/local/lib/python3.7/dist-packages (2.2.1)
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: pymongo[srv] in /usr/local/lib/python3.7/dist-packages (4.3.2)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.7/dist-packages (from pymongo[srv]) (2.2.1)

In [2]:
import pymongo
client = pymongo.MongoClient("mongodb+srv://gaudhamiratheesh4:1234@cluster0.78oa5.mongodb.net/?retryWrites=true&w=majority")
db=client.test

In [3]:
import pymongo
client = pymongo.MongoClient("mongodb+srv://gaudhamiratheesh4:1234@cluster0.78oa5.mongodb.net/?retryWrites=true&w=majority")
db = client.phonebook
records=db.contacts

#***phonebook*** ***project***

In [5]:
import sys
import regex as re           #***************************PHONEBOOK***************************
import pandas as pd
import pymongo
client = pymongo.MongoClient("mongodb+srv://gaudhamiratheesh4:1234@cluster0.78oa5.mongodb.net/?retryWrites=true&w=majority")
db = client.phonebook
records=db.contacts


def enter_numbr():
    while True:
        try:
           
            num = int(input('ENTER PHONE NUMBER FOR SEARCHr:'))
            
           
             
        except ValueError:
            #print("invalid number")
            print('SORRY ENTER ONLY NUMBER')
            continue
        else:
            break
    # search in data
    try:
        va = records.find_one({"phone":num},{"name":1,"_id":0})
        print(va)
    except ValueError:
        print('the number you entered is not saved')

# input name
def enter_name():
    while True:
        try:
            name = (input('ENTER NAME FOR SEARCH:'))
        except ValueError:
            print('SORRY ENTER ONLY NAME')
            continue
        else:
            break
    # search in data
    try:
        va1 = records.find_one({"name":name},{"name":1,"phone":1,"_id":0})
        print(va1)
    except ValueError:
        print('NAME NOT FOUND')
def display_all():
  dis=records.find({},{"_id":0,"name":1,"phone":1,"address":1})
  df=pd.DataFrame(dis)
  display(df)
def delete():
   while True:
        try:
           # pattern=re.compile(r'^(?:(?:\+|0{0,2})91(\s*[\ -]\s*)?|[0]?)?[789]\d{9}|(\d[ -]?){10}\d$')
            name1=input("ENTER NAME TO DELETE-->")
           
           
             
        except ValueError:
            print("ENTER ONLY NAME")
            continue
        else:
            break
     #  try:
          #name1=input("enter name to delete")
       #except ValueError:
   while True:
        
            a=records.find_one({"name":name1},{"_id":0})
            print("CONTACT TO DELETE--  :",a)
            if a==name1:
              print("proceed to delete")
            else:
               break
   confirm=input("DELETE yes / no")
   if confirm=="yes":
      # if name1 not in records:
        #  print("name not found")
      # else:
         delt= records.delete_one({"name":name1})
         print("DELETED-->",delt)
         print("UPDATED CONTACTS: ")
         dis=records.find({},{"_id":0,"name":1,"phone":1})
      
         df=pd.DataFrame(dis)
         display(df)
        # x= display(df)
         
   else:
        print("return to main menu")
    
# save new number
def save_number():
    print('CREATE YOUR CONTACTS')
    new_name = input('ADD NEW NAME --:')
    address=input('ENTER THE ADDRESS')
    new_number = input('ADD NEW NUMBER--:')
    regex= '^(?:(?:\+|0{0,2})91(\s*[\ -]\s*)?|[0]?)?[789]\d{9}|(\d[ -]?){10}\d$'
    if re.fullmatch(regex,new_number):
     
        
        records.insert_one({"name":new_name,"phone":new_number,"address":address})
        print('the nunber that you saved is:','\n',new_name,new_number)
        print("VALID PHONE NUMBER***")
    else:
       
        print("INVALID NUMBER")
 
# chose options
def chose():
    while True:
     print("*******CHOOSE A OPTION*******")
     ch1 = input('   1--> create contact\n   2--> search contact\n   3-->display all contacts\n   4-->delete\n   5-->quit\n   ENTER A CHOICE---> : ')
     if ch1 == '2':
            while True:
                ch2 = input('DO YOU LIKE TO LOOK BY \n  "name" or "number":')
                if ch2 == 'name':
                    enter_name()
                    break
                elif ch2 == 'number':
                    enter_numbr()
                    break
                else:
                    print('ENTER ONLY NAME OR NUMBER')
     elif ch1 == '1':
            save_number()
            break
     elif ch1=="3":
            display_all()
            break
     elif ch1=="4":
           delete()
           break
     elif ch1=="5":
          print("THANKYOU VISIT AGAIN")
         
          sys.exit("***ALWAYS WELCOME***")
     else:
          print('type only "create contact" or "search contact"')

while True:
    chose()

*******CHOOSE A OPTION*******
   1--> create contact
   2--> search contact
   3-->display all contacts
   4-->delete
   5-->quit
   ENTER A CHOICE---> : 1
CREATE YOUR CONTACTS
ADD NEW NAME --:monu
ENTER THE ADDRESSabc
ADD NEW NUMBER--:7994821481
the nunber that you saved is:
 monu 7994821481
VALID PHONE NUMBER***
*******CHOOSE A OPTION*******
   1--> create contact
   2--> search contact
   3-->display all contacts
   4-->delete
   5-->quit
   ENTER A CHOICE---> : 3

      name       phone address
0    guvi1  7894561237     NaN
1  prithyu  7994821547     NaN
2     monu  7994821481     abc

*******CHOOSE A OPTION*******
   1--> create contact
   2--> search contact
   3-->display all contacts
   4-->delete
   5-->quit
   ENTER A CHOICE---> : 5
THANKYOU VISIT AGAIN

SystemExit: ignored

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:3334: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)